# Generated by Django 5.2 on 2025-04-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_offer_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='reason',
            field=models.TextField(default='empty reason for now', max_length=250, verbose_name='frequency reason'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='notes',
            field=models.TextField(blank=True, max_length=300, verbose_name='offer notes'),
        ),
    ]
