# Generated by Django 5.2 on 2025-04-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_decisionreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='subjects',
            field=models.TextField(default='migration dummy', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decisionreason',
            name='diagnostic_results',
            field=models.FileField(default=('icl he did shit',), upload_to=''),
            preserve_default=False,
        ),
    ]
