# Generated by Django 5.2 on 2025-04-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_email_sent',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
