# Generated by Django 5.2 on 2025-04-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_offer_offer_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
